#!/usr/bin/python3
"""
Web server setup using Flask
"""
from api.v1.views import app_views
from flask import Flask, jsonify, make_response

# Create Flask application instance
app = Flask(__name__)

# Register blueprint
app.register_blueprint(app_views)

# Define error handler for 404 errors
@app.errorhandler(404)
def not_found(error):
    """ JSON 404 error handler """
    return make_response(jsonify({"error": "Not found"}), 404)

# Main entry point of the application
if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
